apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gpt-oss-app
    app.kubernetes.io/managed-by: kustomize
  name: gpt-oss-svc
  namespace: gpt-oss
spec:
  selector:
    app.kubernetes.io/instance: gpt-oss-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
